#ifndef FUNCIONARIO_H_
#define FUNCIONARIO_H_

//NUNO
//USAR SETS
//DEFINIR OPERADOR <
//O SET FICA NA CLASSE PONTOS DE VENDA, OU NUMA CLASSE COM A INFORMACAO NOVA
//MEMBRO COM STRING DO LOCAL DO PONTO DE VENDA



#endif /* FUNCIONARIO_H_ */
